// src/Table.svelte
<script>
import {flip} from 'svelte/animate';
import {quintInOut} from 'svelte/easing';

export let products = [];
</script>

<table style="margin: 0 auto; font-size: 2rem; text-align: right">
  <tbody>
    <tr>
      <th>id</th>
      <th>rank</th>
    </tr>

    {#each products as p (p.id)}
      <tr class="product-row" animate:flip="{{easing: quintInOut}}" >
        <td>{p.id}</td>
        <td>
          {#if p.rank}
            <span class="product-rank"
            >{p.rank}</span>
          {/if}
        </td>
      </tr>
    {/each}

  </tbody>
</table>

// react-app/src/table/Table.js
import React from 'react';

function Table(props) {
  // console.log(props);
  // console.log(props.products.map);
  return (
    <div className="Table">
      <h4 className="text-center">{props.name || "Data"} Table</h4>
      <table style={{margin: '0 auto', fontSize: `1.5rem`, textAlign: "right"}}>
        <tbody>
          <tr>
            <th>id</th>
            <th>rank</th>
          </tr>
          {props.products.map(({id, rank}, i) => {
            return (
              <tr className="product-row" key={i}
                  // animate:flip="{{easing: quadInOut}}" 
                >
                <td className="product-id">{id}</td>
                <td>
                    <span className="product-rank"
                          // class:strike="{p.isIncorrectValue}"
                      >{rank}</span>
                </td>
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  );
}

export default Table;
