// react-app/src/App.js
import React, {useState} from 'react';
import logo from './logo.svg';
import './App.css';
import Table from './table/Table';

import {script} from './script';

function App() {
  let buttonText = "button";
  let dialouge = "Hello";
  function executeOp() {

  }
  const [scene, setScene] = useState(script());
  const [products, setProducts] = useState([]);

  return (
    <main>
      <div className="container vertical-center">
        <div className="row">

          <div className="col-xs-12 col-md-6" id="table-col">
            <Table products={products} name="Product"></Table>
          </div>

          <div className="col-xs-12 col-md-6 order-md-2 vertical-center"
              id="explanation">
            <p className="lead">{dialouge}</p>
            <button onClick={() => {
              const {value, done} = scene.next();
              
              setProducts(value);
              setScene(scene);
            }}>{buttonText}</button>
          </div>

        </div>
      </div>
      
    </main>
  );
}

export default App;

// src/App.svelte
<script>
  //   - make button position static
  // replaying a scene could be helpful
  // BUG: ranks of 0 don't render the string "0". it just shows nothing

  import {writable} from 'svelte/store'
  import Table from './Table/Table.svelte';
  export let script = function* () { };
  export let products = writable([]);

  function noop() { }

  let dialouge = "";
  let buttonText = "";
  let op = noop;
  function advanceScript() {
    const {value: beat, done: sceneIsOver} = scene.next();
    if (sceneIsOver) { 
     
     op = () => {
       dialouge = "I hope you enjoyed this demo :)"
       buttonText = "I did!";
     }
    } else {
      [dialouge, op, buttonText] = beat;
    }

  }

  function executeOp() {
    if (typeof op === "function") op();
    advanceScript();
  }

  const scene = script(products);
  advanceScript();

</script>

<main style="height: 100%;">
  <div class="container vertical-center">
    <div class="row">
      <div class="col-xs-12 col-md-6 order-md-2 vertical-center">
        <p class="lead">{dialouge}</p>
        <button on:click="{executeOp}">{buttonText}</button>
      </div>

      <div class="col-xs-12 col-md-6">
        <Table products="{$products}" name="Product"></Table>
      </div>
    </div>
  </div>
  
</main>

<style>
main {
}

.vertical-center {
  display: flex;
  flex-flow: column nowrap;
  justify-content: center;
}

@keyframes appear {
  from { opacity: 0; }
  to   { opacity: 1; }
}
</style>
